### ISSUE TITLE
11.3 Keygen does not generate a password when pressed:(

### ISSUE THREAD

**Issue by liyezhou** [hexinal/mathematica-keygen#2]
I would appreciate it if you could point out how I may have used it the wrong way.

**Comment by liyezhou** [comment]
found the problem / fix:

Add this "  <div id="output"></div>" into the <Body> section, like I did below.

<body>
  <h2>Mathematica 11.3</h2>
  <p>  <br/><br/>Input given MathID (xxxx-xxxxx-xxxxx), whatever Activation Key (xxxx-xxxx-xxxxxx) and press Generate.</p>
  <input type="text" id="str"/>
  <input type="text" id="act"/>
  <button class="btn" onclick="genFromMathId()">Generate</button>
  <br/>   
  <div id="output"></div>
</body>

**Comment by cxwx** [comment]
pls help push it

**Comment by hexinal** [comment]
For some reason, I did not receive notifications on this.. The proposed fix has been merged sorry for the inconvenience.
