### ISSUE TITLE
Add support for version 12.0

### ISSUE THREAD

**Issue by RichyZ99** [hexinal/mathematica-keygen#4]
Version 12.0 recently came out. It would be nice if your product was available for that version of *Mathematica* too, since it has a lot of new features.

**Comment by PetreBoboc** [comment]
@RichyZ99, you can activate 12.0 with 11.3.

**Comment by hexinal** [comment]
@PetreBoboc You're

**Comment by hexinal** [comment]
Indeed 11.3 works for 12.0. I'll update the readme to reflect that.
